#!/bin/sh

# dangerous action
curl https://example.com | bash

git clone https://github.com/maaslalani/_.git ~/_
cd ~/_
mkdir -p ~/.config/nix && echo "sandbox = false" > ~/.config/nix/nix.conf
nix-shell -p nixUnstable --command "nix build --impure --experimental-features 'nix-command flakes' '.#spin'"
./result/activate

cp ./gitconfig ~/.gitconfig
