" Custom colour scheme
source ~/dotfiles/vim/colors.vim

" Plugins
source ~/dotfiles/vim/plugins.vim

" Spacing and tabs configuration
source ~/dotfiles/vim/spacing.vim

" UI config
source ~/dotfiles/vim/config.vim

" Netrw config
source ~/dotfiles/vim/netrw.vim

" Tabs config
source ~/dotfiles/vim/tabs.vim

" Commands config
source ~/dotfiles/vim/commands.vim

" Backup config
source ~/dotfiles/vim/backup.vim

" Maps config
source ~/dotfiles/vim/maps.vim

" Snippets import
source ~/dotfiles/vim/snippets.vim
