DOTFILES=~/dotfiles/vim

" Custom colour scheme
source $DOTFILES/colors.vim

" Spacing and tabs configuration
source $DOTFILES/spacing.vim

" UI config
source $DOTFILES/config.vim

" Netrw config
source $DOTFILES/netrw.vim

" Commands config
source $DOTFILES/commands.vim

" Backup config
source $DOTFILES/backup.vim

" Maps config
source $DOTFILES/maps.vim

" Snippets import
source $DOTFILES/snippets.vim
