" custom colour scheme
source ~/dotfiles/vim/colors.vim

" plugins
source ~/dotfiles/vim/plugins.vim

" spacing and tabs configuration
source ~/dotfiles/vim/spacing.vim

" config
source ~/dotfiles/vim/config.vim

" windows config
source ~/dotfiles/vim/windows.vim

" tabs config
source ~/dotfiles/vim/tabs.vim

" commands config
source ~/dotfiles/vim/commands.vim

" backup config
source ~/dotfiles/vim/backup.vim

" maps config
source ~/dotfiles/vim/maps.vim

" snippets import
source ~/dotfiles/vim/snippets.vim
