DOTFILES=~/dotfiles/.zsh

# variables
source $DOTFILES/variables.zsh

# plugins
source $DOTFILES/plugins.zsh

# aliases
source $DOTFILES/aliases.zsh

# syntax highlighting
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# oh my zsh
source $ZSH/oh-my-zsh.sh
