# taps
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "heroku/brew"

# brews
brew "vim"
brew "tmux"
brew "ripgrep"
brew "fd"
brew "ruby"
brew "node"
brew "git"
brew "tldr"
brew "htop"

# casks
cask "alacritty"
cask "spotify"
cask "slack"
cask "docker"
cask "notion"
