# variables
source ~/dotfiles/zsh/variables.zsh

# plugins
source ~/dotfiles/zsh/plugins.zsh

# aliases
source ~/dotfiles/zsh/aliases.zsh

# oh my zsh
source ~/.oh-my-zsh/oh-my-zsh.sh

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
[ -f /opt/dev/dev.sh ] && source /opt/dev/dev.sh
