DOTFILES=~/dotfiles/zsh

# variables
source $DOTFILES/variables.zsh

# plugins
source $DOTFILES/plugins.zsh

# aliases
source $DOTFILES/aliases.zsh

# oh my zsh
source $ZSH/oh-my-zsh.sh

[ -f /opt/dev/dev.sh ] && source /opt/dev/dev.sh
